### ISSUE TITLE
Linux builds fail, searching for LAPACK

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/build-shtools#12]
This repo builds macOS, linux, and windows wheels for the [pyshtools](https://github.com/SHTOOLS/SHTOOLS/) project, which are then uploaded to pypi. The particularities of this project are that it compiles a bunch of fortran 95 files, and then needs to link to the fftw3, lapack, and blas libraries. This is all specified in the setup.py file of the project, which makes use of the `numpy.distutils.system_info.get_info()` function.

We have used multibuild for this purpose over the past 2 years or so with no major problems with linux, macOS and windows. Our last release was in March, and all three architectures built fine. With a new release a couple of days ago, the windows and macOS builds were successful, but the linux builds failed (usually it is the other way around!). As far as I can tell from the log output, the failure occurs within the setup.py file when the system is trying to find the locations of the fftw, lapack, and blas libraries. It appears that fftw was located ok, but the last messages are about LAPACK not being found, and that we might want to try setting our LAPACK environment variable to point to it.

The last logs are found here: https://travis-ci.org/github/SHTOOLS/build-shtools/builds/727370266

ping @mattip

**Comment by mattip** [comment]
`MANYLINUX_URL` is used in `./multibuild/common_utils.sh` as a location to `pip install` your `TEST_DEPENDS` from. You have `TEST_DEPENDS="$NP_TEST_DEP pytest pytest-xdist pytest-faulthandler pytest-env versioneer"` in your `.travis.yml`, where `NP_TEST_DEP=numpy`. So before testing your package, you will run `pip install numpy pytest pytest-xdist pytest-faulthandler pytest-env versioneer --find-links $MANYLINUX_URL`. 

Bottom line, that should be harmless, but you could remove `MANYLINUX_URL` from the `.travis.yml`.

Now as for the build log you linked to. 

In your `.config.sh` you have `build_openblas; build_fftw`. But [I don't see `build_blas`](https://travis-ci.org/github/SHTOOLS/build-shtools/jobs/727370267#L602) actually starting. Maybe add a `set -x`into the `pre_build` function so you get a report of what is going on in that function. As far as I can tell, that should be setting up openblas. You may need to change the `GF_LIB_URL` used in `multibuild/_gfortran_utils`. Perhaps you could try putting `GF_LIB_URL=https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.9-452-g349b722d/download/` near the top of `config.sh`, and also update `OPENBLAS_VERSION=0.3.9` 


~Note you cannot use wheelhouse any more. You could use testpypi.org for test uploading wheels, like in this PR from scikit-learn MacPython/scikit-learn-wheels#65~ Edit: you are not using wheelhouse, sorry.

**Comment by MarkWieczorek** [comment]
Thanks, you are right that `MANYLINUX_URL` isn't necessary (nor is `WHEELHOUSE_UPLOADER_USERNAME`, not sure why that was there...)

**Comment by mattip** [comment]
By dropping manylinux1 in favor of manylinux2010 you move off CentOS5 (which is long dead) to CentOS6 (which will EOL soon). This will make your yum installations happier. I wrote a [blog post about this](https://labs.quansight.org/blog/2020/11/manylinux1-is-obsolete-manylinux2010-is-almost-eol-what-is-next/). The only reason to stay with manylinux1 was to support pre-pep-19 which was the default in python3.6.

**Comment by mattip** [comment]
The build failure mentioned in the [multibuild issue](https://github.com/matthew-brett/multibuild/issues/325#issuecomment-761882685) is due to the [curl command a](https://github.com/SHTOOLS/build-shtools/runs/1718060706?check_suite_focus=true#step:8:150) failing to download from https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com. You should update your multibuild version to latest devel, which has a correct URL. Something like
```
cd multibuild
git checkout -f devel
git pull
cd ..
git commit -am"update multibuild"
```

**Comment by MarkWieczorek** [comment]
Thanks: switching from master to devel solves almost all problems.

The only problem I encountered is for macOS Python 3.9 where a brew error causes the build to stop:

```
 + brew install gcc
[...]
Error: gcc 10.2.0 is already installed
To upgrade to 10.2.0_2, run `brew upgrade gcc`.
```
On the other hand, python 3.7 and 3.8 work fine on macOS!

**Comment by mattip** [comment]
Could you add `set -ex` [here](https://github.com/SHTOOLS/build-shtools/blob/master/.github/workflows/build_wheels.yml#L74) so it is clear what commands are being called?

**Comment by MarkWieczorek** [comment]
Here is the output with `set -ex` : https://github.com/SHTOOLS/build-shtools/actions/runs/498120582

Stangely, all the macOS builds are failing now. 

I think that the problem is that instead of just running `brew install gcc` you need to use `brew reinstall gcc` (this is what I use with my github CI tests). Alternatively, you might be able to just ignore the error message somehow.

**Comment by mattip** [comment]
The `brew install gcc` comes from [this repo](https://github.com/SHTOOLS/build-shtools/blob/master/config.sh#L16). What happens if you remove that line?

Edit: by "this repo" I mean it is local to the build-shtools repo.

**Comment by MarkWieczorek** [comment]
I got everything to work, but I suspect that there is some kind of issue with how github actions sets up the python 3.9 environment. For 3.9, in needed to change `brew install gcc` to `brew reinstall gcc`. This also works on 3.7 and 3.8, but it is not necessary to do so. For 3.9, if you don't reinstall gcc, I believe that it searches for the system gcc, and this doesn't have gfortran installed.

Thanks for helping once again!
