### ISSUE TITLE
Linux builds fail because libopenblas.so is not found

### ISSUE THREAD

**Issue by MarkWieczorek** [SHTOOLS/build-shtools#14]
In this release of pyshtools, multibuild works perfectly for macOS, but fails for linux:

https://github.com/SHTOOLS/build-shtools/actions/runs/1166019653

As far as I can tell, everything is being built properly for linux. However, after the `_SHTOOLS` module is built, when it is imported, we get an error saying that `libopenblas.so.0` can not be found:
```
---- BUILDING DOCS ----
  creating build/lib.linux-x86_64-3.9/pyshtools/doc
  Traceback (most recent call last):
    File "/tmp/pip-wheel-m5ct70ax/pyshtools_6a531a075c2d460e98b203c71eb2408d/build/lib.linux-x86_64-3.9/pyshtools/make_docs.py", line 12, in <module>
      import _SHTOOLS
  ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```
Earlier in the build, I can see this the openblas is being dowloaded correctly, and I don't see any obvious errors related to `build openblas`, so I'm at a bit of a loss as to what to do.

@mattip - sorry to bother you again :(

**Comment by mattip** [comment]
You are [unpacking openblas from /](https://github.com/SHTOOLS/build-shtools/runs/3420551215?check_suite_focus=true#step:6:308). I think you should run `ldconfig` to rebuild the cache so that `ld` knows a new file is preset before building.

**Comment by MarkWieczorek** [comment]
That was easy. Changing the relevant part of config.sh to 
```
build_openblas
ldconfig
build_fftw
```
worked! Thanks again.

**Comment by mattip** [comment]
@matthewbrett is calling `ldconfig` something that should be done by multibuild in [`build_openblas`](https://github.com/matthew-brett/multibuild/blob/cdffc52846355707f389808414cf8dfe31289328/library_builders.sh#L129)?

**Comment by MarkWieczorek** [comment]
I don't know, probably? I doesn't feel right that I need to do this myself, but now that I now the problem, I don't mind putting the extra line of code in the config file. I didn't have this problem before, so its possible that something changed upstream somewhere.
